### ISSUE TITLE
Different workspaces produce different hashes

### ISSUE THREAD

**Issue by erikkerber** [Tinder/bazel-diff#180]
Let me know if "feature" or "bug"

Assume a Bazel repo in `/a`:

```
cd a
bazel run :bazel-diff --script_path=/tmp/bazel-diff
cd ..

/tmp/bazel-diff generate-hashes --workspacePath=/a /tmp/a-hash
cp -r a b
/tmp/bazel-diff generate-hashes --workspacePath=/b /tmp/b-hash
cmp /tmp/a-hash /tmp/b-hash
```

As a background — we're caching the hash results to avoid too many Git checkouts/fetches in builds, but finding out that different workspaces result in different results. The workspaces are a boring implementation detail of our CI system which different paths/checkouts for different jobs.

**Comment by aarontsharp** [comment]
We are also trying to accomplish similar as our CI system by default does shallow clones and we likewise want to avoid switching branches and calculating hashes for previous builds. I've found unless the hashes are generated on the exact same machine, they're always different. In our case, even different CI runner instances with otherwise identical configuration, OS, file systems, etc always produce different hashes.

Looking into the hashing strategy, there are some obvious target attributes that could always influence the hash. For example, `location` appears to be an absolute path, so even if the target's workspace path is the same, that would always hash differently if the absolute path isn't consistent. I expect there are other attributes that similarly always hash differently even if they're functionally identical.

**Comment by tinder-maxwellelliott** [comment]
Can you test out https://github.com/Tinder/bazel-diff/pull/182 and let me know how it works, if it works we can find a way to set the list of ignored attributes when hashing

**Comment by erikkerber** [comment]
@tinder-maxwellelliott 100% did the trick. Awesome 🙇🏼

**Comment by tinder-maxwellelliott** [comment]
Okay Ill work on making it so the list of ignored attributes can be provided by an end user

**Comment by tinder-maxwellelliott** [comment]
@erikkerber Can you do one last test with https://github.com/Tinder/bazel-diff/pull/182, I added the ability to list attributes you wish to ignore during rule target hashing

**Comment by aarontsharp** [comment]
@tinder-maxwellelliott #182 I think this worked for me, thanks! I had to add `location` and `path` to the ignore list. In my case, I observed many of the external rules (like `bazel_tools`) always seemed to have a different `path` in our different runners. I'm testing this out in our CI environment now, but I think this likely addresses the issues we were seeing. Thanks again!

**Comment by tinder-maxwellelliott** [comment]
Awesome, I'll close this then and merge it in. Thanks Y'all

**Comment by jieyu** [comment]
I was trying to use the `--ignoredRuleHashingAttributes` flag to ignore certain attributes from a rule. So I have a rule that has a private attribute `_go_vendor_modules_txt` that is a filegroup. when compute hashes, I set `--ignoredRuleHashingAttributes=_go_vendor_modules_txt`. However, when trying to get impacted targets, it seems that the change of files in `_go_vendor_modules_txt` is still not ignored. Anything I did wrong?

**Comment by tinder-maxwellelliott** [comment]
> I was trying to use the `--ignoredRuleHashingAttributes` flag to ignore certain attributes from a rule. So I have a rule that has a private attribute `_go_vendor_modules_txt` that is a filegroup. when compute hashes, I set `--ignoredRuleHashingAttributes=_go_vendor_modules_txt`. However, when trying to get impacted targets, it seems that the change of files in _go_vendor_modules_txt is still not ignored. Anything I did wrong?

Is this a rule attribute? Last I checked the proto I saw nothing like `_go_vendor_modules_txt`

**Comment by jieyu** [comment]
@tinder-maxwellelliott it's a custom rule in house.
